#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import shutil
import argparse
sys.path.append('/usr/lib/webwin')
from ww_util import WwUtil
from ww_param import WwParam
from ww_daemon import WwDaemon

# parse parameter
parseResult = None
if True:
    argParser = argparse.ArgumentParser()
    argParser.add_argument("--pid-file", dest='pid_file', help="Specify location of a PID file.")
    argParser.add_argument("-d", "--debug-level", dest='debug_level',
                           choices=['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'], default="INFO",
                           help="Set output debug message level")
    parseResult = argParser.parse_args()

param = WwParam()

try:
    # fill WrtParam according to argument
    if parseResult.pid_file is not None:
        param.pidFile = parseResult.pid_file
    param.logLevel = parseResult.debug_level

    # create directories
    WwUtil.ensureDir(param.logDir)
    WwUtil.mkDirAndClear(param.tmpDir)
    WwUtil.mkDirAndClear(param.runDir)

    # start server
    param.daemon = WwDaemon(param)
    param.daemon.run()
finally:
    if os.path.exists(param.tmpDir):
        shutil.rmtree(param.tmpDir)
    if os.path.exists(param.runDir):
        shutil.rmtree(param.runDir)
